### ISSUE TITLE
Where is document.readyState property?

### ISSUE THREAD

**Issue by kalopsia** [dominikh/go-js-dom#20]
Thanks for the great job!) Today I started to play around with your package and couldn't get it work. The first thing what I did is include compiled main.js file into `<head>` tag. However whatever selector I use (`dom.GetWindow().Document().querySelector("...")`) - it returned nil. The problem was I need to include the file before `body` close tag!) So where is DOM's `readyState` property?

**Comment by kalopsia** [comment]
I've found it using `js.Global.Get("document").Get("readyState")`. But it is always has `loading` state( Could give an example how can I eg run `println("ready!")` after DOM is loaded?

**Comment by shurcooL** [comment]
What does it print if you do this?

```Go
func main() {
	document.AddEventListener("DOMContentLoaded", false, func(_ dom.Event) {
		println(js.Global.Get("document").Get("readyState"))
	})
}
```

**Comment by kalopsia** [comment]
The output is `interactive`.

**Comment by shurcooL** [comment]
> The first thing what I did is include compiled main.js file into `<head>` tag. However whatever selector I use (`dom.GetWindow().Document().querySelector("...")`) - it returned nil.

That's because the body does not yet exist when the script runs in `<head>`. However, if you delay the execution of your code by calling it from the `DOMContentLoaded` event listener, then body and its elements should be ready by then, so `QuerySelector` should work.

**Comment by kalopsia** [comment]
Of course, I know it. But I thought (I don't know why) that the gopherjs compile into the code that start only when dom is ready)) Thank you for explanation and very good example! If `readyState` property defined in DOM specification and it is implemented in all (almost) browsers - why not to include it to the package itself?)

**Comment by shurcooL** [comment]
> If `readyState` property defined in DOM specification and it is implemented in all (almost) browsers - why not to include it to the package itself?)

I don't think there's a reason not to, it's just not done yet (there are a few not yet implemented features, e.g., see [dom.go#L950](https://github.com/dominikh/go-js-dom/blob/5f25eefafd064224f9e3f99d71796c68addbcf86/dom.go#L950)).

I believe that contributions are welcome (@dominikh, correct if wrong), so feel free to make a PR that adds it if you can/want (since there's no CONTRIBUTING.md file that has special contribution guidelines in this repo, making PRs is the default approach). Thanks!

**Comment by dominikh** [comment]
It's already implemented, as `HTMLDocument.ReadyState`. `HTMLDocument` is an interface, `ReadyState` in turn a method.

An example of accessing it:

```
dom.GetWindow().Document().(dom.HTMLDocument).ReadyState()
```

`Window.Document` returns the `Document` interface, because not all uses of DOM have to be in the context of HTML (SVG would be another context, for example). If you know that you're working with HTML, you can type assert to the `HTMLDocument` interface.

For documentation on all the types and methods, see http://godoc.org/honnef.co/go/js/dom.

**Comment by kalopsia** [comment]
Good!) Thanks you)
